/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 * Imports.
 */
import Classes.*;
import java.awt.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author jumanah
 */
public class SignUp extends javax.swing.JFrame {

    static SignUp window = new SignUp();
    boolean emailCheck, passCheck, repassCheck, usernameCheck, fNameCheck, lNameCheck;
    int count = 0;

    /**
     * Creates new form sign up
     */
    public SignUp() {
        initComponents();
        setTitle("Sign Up");
        show.setVisible(false);
        hide.setVisible(false);
        passText.setEchoChar((char) 0);
        rePassText.setEchoChar((char) 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        signUp = new javax.swing.JButton();
        emailText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        FnameText = new javax.swing.JTextField();
        LnameText = new javax.swing.JTextField();
        checkInfo = new javax.swing.JCheckBox();
        hint2 = new javax.swing.JLabel();
        hint1 = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        hide = new javax.swing.JLabel();
        passText = new javax.swing.JPasswordField();
        rePassText = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(197, 300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/welcome.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 340, 400, 420));

        jLabel5.setFont(new java.awt.Font("Sinhala MN", 1, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(161, 195, 252));
        jLabel5.setText("Welcome To ALHK Family");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sinhala MN", 2, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 74, 71));
        jLabel1.setText("Make your education joyful");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 330, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Material Sharp-Sparkling.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Material Sharp-Sparkling.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 750));

        jPanel2.setBackground(new java.awt.Color(161, 195, 252));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-iOS Glyph-Multiply.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, -1));

        signUp.setBackground(new java.awt.Color(161, 195, 252));
        signUp.setFont(new java.awt.Font("Sinhala MN", 0, 20)); // NOI18N
        signUp.setForeground(new java.awt.Color(255, 255, 255));
        signUp.setText("Sign Up");
        signUp.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        signUp.setContentAreaFilled(false);
        signUp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        signUp.setEnabled(false);
        signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpActionPerformed(evt);
            }
        });
        jPanel2.add(signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 460, 40));

        emailText.setBackground(new java.awt.Color(161, 195, 252));
        emailText.setFont(new java.awt.Font("Sinhala MN", 0, 20)); // NOI18N
        emailText.setForeground(new java.awt.Color(255, 255, 255));
        emailText.setText("Email");
        emailText.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        emailText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailTextMousePressed(evt);
            }
        });
        jPanel2.add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 460, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Pastel Glyph-Paper Plane.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        usernameText.setBackground(new java.awt.Color(161, 195, 252));
        usernameText.setFont(new java.awt.Font("Sinhala MN", 0, 20)); // NOI18N
        usernameText.setForeground(new java.awt.Color(255, 255, 255));
        usernameText.setText("Username");
        usernameText.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        usernameText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usernameTextMousePressed(evt);
            }
        });
        jPanel2.add(usernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 460, 40));

        FnameText.setBackground(new java.awt.Color(161, 195, 252));
        FnameText.setFont(new java.awt.Font("Sinhala MN", 0, 20)); // NOI18N
        FnameText.setForeground(new java.awt.Color(255, 255, 255));
        FnameText.setText("First Name");
        FnameText.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        FnameText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FnameTextMousePressed(evt);
            }
        });
        jPanel2.add(FnameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 460, 40));

        LnameText.setBackground(new java.awt.Color(161, 195, 252));
        LnameText.setFont(new java.awt.Font("Sinhala MN", 0, 20)); // NOI18N
        LnameText.setForeground(new java.awt.Color(255, 255, 255));
        LnameText.setText("Last Name");
        LnameText.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        LnameText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LnameTextMousePressed(evt);
            }
        });
        jPanel2.add(LnameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 460, 40));

        checkInfo.setFont(new java.awt.Font("Sinhala MN", 0, 14)); // NOI18N
        checkInfo.setForeground(new java.awt.Color(255, 255, 255));
        checkInfo.setText("Check My Information");
        checkInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInfoActionPerformed(evt);
            }
        });
        jPanel2.add(checkInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 190, -1));

        hint2.setFont(new java.awt.Font("PT Sans", 0, 11)); // NOI18N
        hint2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(hint2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 460, 30));

        hint1.setFont(new java.awt.Font("PT Sans", 0, 12)); // NOI18N
        hint1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(hint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 460, 20));

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-iOS Glyph-Eye.png"))); // NOI18N
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showMousePressed(evt);
            }
        });
        jPanel2.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, -1, -1));

        hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-iOS Glyph-Hide.png"))); // NOI18N
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hideMousePressed(evt);
            }
        });
        jPanel2.add(hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, -1, -1));

        passText.setBackground(new java.awt.Color(161, 195, 252));
        passText.setFont(new java.awt.Font("Sinhala MN", 0, 20)); // NOI18N
        passText.setForeground(new java.awt.Color(255, 255, 255));
        passText.setText("Password");
        passText.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        passText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passTextFocusLost(evt);
            }
        });
        passText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passTextMousePressed(evt);
            }
        });
        jPanel2.add(passText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 460, 40));

        rePassText.setBackground(new java.awt.Color(161, 195, 252));
        rePassText.setFont(new java.awt.Font("Sinhala MN", 0, 20)); // NOI18N
        rePassText.setForeground(new java.awt.Color(255, 255, 255));
        rePassText.setText("Confirm Password");
        rePassText.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        rePassText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rePassTextMousePressed(evt);
            }
        });
        jPanel2.add(rePassText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 460, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 0, 800, 750));

        setSize(new java.awt.Dimension(1350, 778));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpActionPerformed
        // TODO add your handling code here:
        User newUser = new User(usernameText.getText(), FnameText.getText(), LnameText.getText(), emailText.getText(), passText.getText());
        try {
            Database.addUserInfo(newUser);
            JOptionPane.showMessageDialog(null, "Welcome to ALHK! We are glad you are with us.‏");
            SignIn.window.setVisible(true);
            this.setVisible(false);
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "There is an error in some files that occurred during downloading the app, please try to download the ALHK app again.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "There is an error that occurred on the Database server during the connection, please try again later.");
        }
    }//GEN-LAST:event_signUpActionPerformed

    private void usernameTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameTextMousePressed
        // TODO add your handling code here:
        if (count == 2) {
            usernameText.setText("");
            ++count;
        }
    }//GEN-LAST:event_usernameTextMousePressed

    private void FnameTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FnameTextMousePressed
        // TODO add your handling code here:
        if (count == 0) {
            FnameText.setText("");
            ++count;
        }
    }//GEN-LAST:event_FnameTextMousePressed

    private void LnameTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LnameTextMousePressed
        // TODO add your handling code here:
        if (count == 1) {
            LnameText.setText("");
            ++count;
        }
    }//GEN-LAST:event_LnameTextMousePressed

    private void emailTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTextMousePressed
        // TODO add your handling code here:
        if (count == 3) {
            emailText.setText("");
            ++count;
        }
    }//GEN-LAST:event_emailTextMousePressed

    private void checkInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInfoActionPerformed
        // TODO add your handling code here:
        try {
            //Check the first name
            String NAME_PATTERN = "^[\\p{L}.'-]+";
            if (true) {
                if (FnameText.getText().isEmpty() || !FnameText.getText().matches(NAME_PATTERN)) {
                    FnameText.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.RED));
                    fNameCheck = false;
                    checkInfo.setSelected(false);
                } else {
                    FnameText.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.WHITE));
                    fNameCheck = true;
                }
            }

            //Check the last name
            if (true) {
                if (LnameText.getText().isEmpty() || !LnameText.getText().matches(NAME_PATTERN)) {
                    LnameText.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.RED));
                    lNameCheck = false;
                    checkInfo.setSelected(false);
                } else {
                    LnameText.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.WHITE));
                    lNameCheck = true;
                }
            }
            //Check the username
            if (true) {

                usernameCheck = Database.checkUsername(usernameText.getText());
                if (usernameCheck == false) {
                    usernameText.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.RED));
                    checkInfo.setSelected(false);
                } else {
                    usernameText.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.WHITE));
                }

            }

            //Check email 
            if (true) {

                // TODO add your handling code here:
                emailCheck = Database.checkEmail(emailText.getText());
                String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
                //Found on db or not match the conditions
                if (emailCheck == true || !emailText.getText().matches(EMAIL_PATTERN)) {
                    emailText.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.RED));
                    checkInfo.setSelected(false);
                    //false: because the condition of submit button
                    emailCheck = false;
                } else {
                    emailText.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.WHITE));
                    emailCheck = true;
                }
            }

            //Check password
            if (true) {
                passCheck = User.checkPassword(passText.getText());
                if (passCheck == false) {
                    passText.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.RED));
                    checkInfo.setSelected(false);
                    passCheck = false;
                } else {
                    passText.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.WHITE));
                    passCheck = true;
                }
            }

            //Check repeate password
            if (true) {
                if (passText.getText().equals(rePassText.getText())) {
                    repassCheck = true;
                    rePassText.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.WHITE));

                } else {
                    repassCheck = false;
                    rePassText.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.RED));
                    checkInfo.setSelected(false);
                }
            }

            if (emailCheck && passCheck && repassCheck && usernameCheck && fNameCheck && lNameCheck) {
                hide.setVisible(false);
                show.setVisible(false);
                signUp.setEnabled(true);
            }
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "There is an error in some files that occurred during downloading the app, please try to download the ALHK app again.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "There is an error that occurred on the Database server during the connection, please try again later.");
        }
    }//GEN-LAST:event_checkInfoActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        dispose();
        Home.window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_exitMouseClicked

    private void showMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMousePressed
        // TODO add your handling code here:
        show.setVisible(false);
        hide.setVisible(true);
        passText.setEchoChar((char) 0);
        rePassText.setEchoChar((char) 0);
    }//GEN-LAST:event_showMousePressed

    private void passTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTextMousePressed
        // TODO add your handling code here:
        if (count == 4) {
            passText.setText("");
            ++count;
            hide.setVisible(true);
            show.setVisible(false);
        }
        hint1.setText("Password must be between 8-15 characters, include UPPER and lower case letters");
        hint2.setText("numbers, special character [e.g. @,_,-] and no space.");
    }//GEN-LAST:event_passTextMousePressed

    private void rePassTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rePassTextMousePressed
        // TODO add your handling code here:
        if (count == 5) {
            rePassText.setText("");
            ++count;
        }

    }//GEN-LAST:event_rePassTextMousePressed

    private void hideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMousePressed
        // TODO add your handling code here:
        hide.setVisible(false);
        show.setVisible(true);
        passText.setEchoChar('*');
        rePassText.setEchoChar('*');
    }//GEN-LAST:event_hideMousePressed

    private void passTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTextFocusLost
        // TODO add your handling code here:
        hint1.setText("");
        hint2.setText("");
    }//GEN-LAST:event_passTextFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FnameText;
    private javax.swing.JTextField LnameText;
    private javax.swing.JCheckBox checkInfo;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel hide;
    private javax.swing.JLabel hint1;
    private javax.swing.JLabel hint2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField passText;
    private javax.swing.JPasswordField rePassText;
    private javax.swing.JLabel show;
    private javax.swing.JButton signUp;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
