/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 * Imports.
 */
import java.awt.*;
import Classes.*;
import java.io.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jumanah
 */
public class Tutorials extends javax.swing.JFrame {

    static Tutorials window = new Tutorials();

    /**
     * Creates new form tutorials
     */
    public Tutorials() {
        initComponents();
        setTitle("ALHK Video Tutorials");
        //Interface design
        ALHKProject.setColor(btnVideo);
        ALHKProject.resetColor(btnHome, btnSection, btnProfile);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        hologram = new javax.swing.JButton();
        leap = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnProfile = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnVideo = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        btnSection = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Sinhala MN", 1, 30)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(35, 39, 101));
        jLabel20.setText("Leap Motion Controller");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        jLabel14.setFont(new java.awt.Font("PT Sans Caption", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(92, 140, 215));
        jLabel14.setText("A photographic technique that records the light");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel15.setFont(new java.awt.Font("PT Sans Caption", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(92, 140, 215));
        jLabel15.setText("scattered from an object, and then presents it in");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel21.setFont(new java.awt.Font("PT Sans Caption", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(92, 140, 215));
        jLabel21.setText("a way that appears three-dimensional.");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Sinhala MN", 1, 30)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(35, 39, 101));
        jLabel22.setText("3D Hologram Display");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel25.setFont(new java.awt.Font("PT Sans Caption", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(92, 140, 215));
        jLabel25.setText("A computer hardware sensor device that supports ");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        jLabel26.setFont(new java.awt.Font("PT Sans Caption", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(92, 140, 215));
        jLabel26.setText("hand and finger motion as input, similar to a mouse,");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        jLabel29.setFont(new java.awt.Font("PT Sans Caption", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(92, 140, 215));
        jLabel29.setText("but requires no hand contact or touching.");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        hologram.setBackground(new java.awt.Color(255, 255, 255));
        hologram.setFont(new java.awt.Font("Sinhala MN", 0, 18)); // NOI18N
        hologram.setForeground(new java.awt.Color(92, 140, 215));
        hologram.setText("3D Hologram Tutorial");
        hologram.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(92, 140, 215)));
        hologram.setContentAreaFilled(false);
        hologram.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        hologram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hologramActionPerformed(evt);
            }
        });
        jPanel2.add(hologram, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 200, 40));

        leap.setBackground(new java.awt.Color(255, 255, 255));
        leap.setFont(new java.awt.Font("Sinhala MN", 0, 18)); // NOI18N
        leap.setForeground(new java.awt.Color(92, 140, 215));
        leap.setText("Leap Motion Tutorial");
        leap.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(92, 140, 215)));
        leap.setContentAreaFilled(false);
        leap.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        leap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leapActionPerformed(evt);
            }
        });
        jPanel2.add(leap, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/leap.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 370, 230));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3DHologram.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 370, 230));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 0, 1010, 750));

        jPanel1.setBackground(new java.awt.Color(161, 195, 252));
        jPanel1.setPreferredSize(new java.awt.Dimension(197, 300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProfile.setBackground(new java.awt.Color(92, 140, 215));
        btnProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Fluency System Regular-User.png"))); // NOI18N
        btnProfile.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel13.setFont(new java.awt.Font("Sinhala MN", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Profile");
        btnProfile.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 16, -1, -1));

        jPanel1.add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 350, 50));

        btnVideo.setBackground(new java.awt.Color(92, 140, 215));
        btnVideo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVideoMouseClicked(evt);
            }
        });
        btnVideo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Material Outlined-Video.png"))); // NOI18N
        btnVideo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("Sinhala MN", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Devices Tutorial");
        btnVideo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 16, -1, -1));

        jPanel1.add(btnVideo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 350, 50));

        jLabel3.setFont(new java.awt.Font("Sinhala MN", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ALHK");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        btnHome.setBackground(new java.awt.Color(92, 140, 215));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        btnHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Fluency System Regular-Home.png"))); // NOI18N
        btnHome.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel24.setFont(new java.awt.Font("Sinhala MN", 0, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Home");
        btnHome.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 16, -1, -1));

        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 350, 50));

        btnLogOut.setBackground(new java.awt.Color(161, 195, 252));
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
        });
        btnLogOut.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Windows 10-Logout Rounded Left.png"))); // NOI18N
        btnLogOut.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel28.setFont(new java.awt.Font("Sinhala MN", 0, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Log Out");
        btnLogOut.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 16, -1, -1));

        jPanel1.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 350, 50));

        jLabel31.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 270, 20));

        btnSection.setBackground(new java.awt.Color(92, 140, 215));
        btnSection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSectionMouseClicked(evt);
            }
        });
        btnSection.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Material Outlined-Four Squares.png"))); // NOI18N
        btnSection.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel37.setFont(new java.awt.Font("Sinhala MN", 0, 20)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Section");
        btnSection.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 16, -1, -1));

        jPanel1.add(btnSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 350, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 750));

        setSize(new java.awt.Dimension(1350, 776));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hologramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hologramActionPerformed
        // TODO add your handling code here:
        try {
            //Open 3d hologram display tutorial
            Desktop.getDesktop().open(new File("Video Tutorials/Hologram Tutorial.mov"));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "The Tutorial video you are looking for is not available anymore.");
        }
    }//GEN-LAST:event_hologramActionPerformed

    private void leapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leapActionPerformed
        // TODO add your handling code here:
        try {
            //Open leap motion controller tutorial
            Desktop.getDesktop().open(new File("Video Tutorials/Leap Tutorial.mov"));
        } catch (IOException ex) {           
            JOptionPane.showMessageDialog(null, "The Tutorial video you are looking for is not available anymore.");
        }
    }//GEN-LAST:event_leapActionPerformed

    private void btnVideoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVideoMouseClicked
        // TODO add your handling code here:
        Tutorials.window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVideoMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        Home.window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
        // TODO add your handling code here:
        dispose();
        Home.window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogOutMouseClicked

    private void btnSectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSectionMouseClicked
        // TODO add your handling code here:
        Section window = new Section();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSectionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tutorials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tutorials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tutorials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tutorials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tutorials().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnLogOut;
    private javax.swing.JPanel btnProfile;
    private javax.swing.JPanel btnSection;
    private javax.swing.JPanel btnVideo;
    private javax.swing.JButton hologram;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton leap;
    // End of variables declaration//GEN-END:variables
}
